spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://192.168.148.129:3306/blog?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    com.wenting.blog: debug
  file: log/blog.log


